import { Game, GameCondition, GameStatus, Session, Venue } from "./db/types";

export const mockVenues: Venue[] = [
  {
    id: "venue-1",
    owner_id: "owner-1",
    name: "Atlas Boardroom",
    slug: "atlas-boardroom",
    logo_url: null,
    description: "A cozy board game cafe with over 500 games",
    website_url: null,
    phone: null,
    email: null,
    social_instagram: null,
    social_facebook: null,
    cover_image_url: null,
    is_active: true,
    created_at: "2024-01-04T12:00:00Z",
  },
  {
    id: "venue-2",
    owner_id: "owner-1",
    name: "Rook & River Annex",
    slug: "rook-river-annex",
    logo_url: null,
    description: null,
    website_url: null,
    phone: null,
    email: null,
    social_instagram: null,
    social_facebook: null,
    cover_image_url: null,
    is_active: true,
    created_at: "2024-06-12T12:00:00Z",
  },
];

const now = new Date().toISOString();

const gameBase = {
  venue_id: mockVenues[0].id,
  copies_in_rotation: 1,
  pitch: null,
  setup_steps: null,
  rules_bullets: null,
  cover_image_url: null,
  bgg_id: null,
  bgg_rank: null,
  bgg_rating: null,
  is_staff_pick: false,
  instructional_video_url: null,
};

export const mockGames: Game[] = [
  {
    ...gameBase,
    id: "game-azul",
    title: "Azul",
    min_players: 2,
    max_players: 4,
    min_time_minutes: 30,
    max_time_minutes: 45,
    complexity: "simple",
    vibes: ["calming", "pattern"],
    status: "in_rotation",
    condition: "good",
    shelf_location: "Wall A / 3",
    instructional_video_url: "https://www.youtube.com/watch?v=csJL-78NEPQ",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-cascadia",
    title: "Cascadia",
    min_players: 1,
    max_players: 4,
    min_time_minutes: 30,
    max_time_minutes: 40,
    complexity: "medium",
    vibes: ["nature", "drafting"],
    status: "in_rotation",
    condition: "new",
    shelf_location: "Wall B / 2",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-root",
    title: "Root",
    min_players: 2,
    max_players: 6,
    min_time_minutes: 70,
    max_time_minutes: 120,
    complexity: "complex",
    vibes: ["asymmetric", "conflict"],
    status: "in_rotation",
    condition: "worn",
    shelf_location: "Wall C / 1",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-wingspan",
    title: "Wingspan",
    min_players: 1,
    max_players: 5,
    min_time_minutes: 45,
    max_time_minutes: 70,
    complexity: "medium",
    vibes: ["engine", "serene"],
    status: "in_rotation",
    condition: "good",
    shelf_location: "Wall A / 5",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-gloomhaven",
    title: "Gloomhaven: Jaws of the Lion",
    min_players: 1,
    max_players: 4,
    min_time_minutes: 90,
    max_time_minutes: 150,
    complexity: "complex",
    vibes: ["campaign", "co-op"],
    status: "out_for_repair",
    condition: "problematic",
    shelf_location: "Repair Bench",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-heat",
    title: "Heat: Pedal to the Metal",
    min_players: 1,
    max_players: 6,
    min_time_minutes: 45,
    max_time_minutes: 70,
    complexity: "medium",
    vibes: ["racing", "push-your-luck"],
    status: "in_rotation",
    condition: "good",
    shelf_location: "Wall D / 4",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-hive",
    title: "Hive",
    min_players: 2,
    max_players: 2,
    min_time_minutes: 20,
    max_time_minutes: 25,
    complexity: "simple",
    vibes: ["abstract", "portable"],
    status: "for_sale",
    condition: "new",
    shelf_location: "Counter Shop",
    created_at: now,
  },
  {
    ...gameBase,
    id: "game-brass",
    title: "Brass: Birmingham",
    min_players: 2,
    max_players: 4,
    min_time_minutes: 80,
    max_time_minutes: 120,
    complexity: "complex",
    vibes: ["economic", "network"],
    status: "in_rotation",
    condition: "good",
    shelf_location: "Wall C / 4",
    created_at: now,
  },
];

export const mockSessions: Session[] = [
  {
    id: "session-1",
    venue_id: mockVenues[0].id,
    table_id: "table-7",
    game_id: "game-azul",
    started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    wizard_params: { playerCount: 3 },
    created_at: now,
    ended_at: null,
    feedback_rating: null,
    feedback_complexity: null,
    feedback_replay: null,
    feedback_comment: null,
    feedback_submitted_at: null,
    feedback_venue_rating: null,
    feedback_venue_comment: null,
    feedback_skipped: false,
    feedback_source: null,
  },
  {
    id: "session-2",
    venue_id: mockVenues[0].id,
    table_id: "table-2",
    game_id: "game-cascadia",
    started_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    wizard_params: { playerCount: 2 },
    created_at: now,
    ended_at: null,
    feedback_rating: null,
    feedback_complexity: null,
    feedback_replay: null,
    feedback_comment: null,
    feedback_submitted_at: null,
    feedback_venue_rating: null,
    feedback_venue_comment: null,
    feedback_skipped: false,
    feedback_source: null,
  },
  {
    id: "session-3",
    venue_id: mockVenues[0].id,
    table_id: "table-4",
    game_id: "game-root",
    started_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    wizard_params: { playerCount: 5 },
    created_at: now,
    ended_at: null,
    feedback_rating: null,
    feedback_complexity: null,
    feedback_replay: null,
    feedback_comment: null,
    feedback_submitted_at: null,
    feedback_venue_rating: null,
    feedback_venue_comment: null,
    feedback_skipped: false,
    feedback_source: null,
  },
];

export type MaintenanceIssue = {
  id: string;
  game_id: string;
  issue: string;
  severity: "low" | "medium" | "high";
  status: GameStatus | "resolved";
  condition: GameCondition;
  notes?: string;
};

export const mockIssues: MaintenanceIssue[] = [
  {
    id: "issue-1",
    game_id: "game-gloomhaven",
    issue: "Missing standees",
    severity: "high",
    status: "out_for_repair",
    condition: "problematic",
    notes: "Bag of monsters misplaced during weekend rush",
  },
  {
    id: "issue-2",
    game_id: "game-root",
    issue: "Box tear",
    severity: "medium",
    status: "in_rotation",
    condition: "worn",
    notes: "Lid corner split, tape applied",
  },
  {
    id: "issue-3",
    game_id: "game-azul",
    issue: "Tile chipped",
    severity: "low",
    status: "in_rotation",
    condition: "good",
  },
];

export const mockTables = [
  { id: "table-1", label: "Table 1" },
  { id: "table-2", label: "Table 2" },
  { id: "table-3", label: "Table 3" },
  { id: "table-4", label: "Table 4" },
  { id: "table-5", label: "Table 5" },
  { id: "table-7", label: "Table 7" },
];
